theme = "apollo"
base_url = "https://woldmann.com"
title = "Falk Woldmann's Homepage"
description = "This is the personal homepage of Falk Woldmann. I am a senior software developer with a passion for building great products and with a constant drive for further improvement and a passion for continuously learning new technologies and methods."
author = "Falk Woldmann"
minify_html = true

[extra]
theme = "auto"
socials = [
  { name = "github", url = "https://github.com/FalkWoldmann/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/falk-woldmann/", icon = "linkedin" },
  { name = "email", url = "mailto:hi@woldmann.com", icon = "email" },
]
menu =  []
